repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/ansible-community/ansible-lint
    rev: v4.2.0
    hooks:
    - id: ansible-lint
      files: \.(yaml|yml)$
