---

- name: "Populate service facts"
  service_facts:

- name: "Service {{ generic_service_name }} state"
  with_items: "{{ generic_service_name }}"
  loop_control:
    loop_var: service
    label: "{{ service }}"
  debug:
    msg: "{{ service }} status: {{ ansible_facts.services[ service ].state }}"