---

- name: "Populate service facts"
  service_facts:

- name: "Service {{ generic_service_name }} state"
  debug:
    msg: "{{ generic_service_name }} status: {{ ansible_facts.services[ generic_service_name ].state }}"